### ISSUE TITLE
Can someone help me understand exactly when/how you use this?

### ISSUE THREAD

**Issue by JohnAllen** [projectchicago/gastoken#11]
So I get that this refunds you gas when you free your tokens.  But to benefit, do you need to be trying to have another tx confirmed at the same time? When and where does the benefit of the refunded gas actually occur?

**Comment by lorenzb** [comment]
Yes. 

Simple example constructed with the help of the calculator on [gastoken.io](//gastoken.io):

You have a contract transaction that would typically cost 400k gas.
As part of the same transaction, you now free 0.10 GST2. As a result, your transaction only costs 242854 gas, a ~40% reduction.
