### ISSUE TITLE
Gastoken deployment on matic network (polygon)?

### ISSUE THREAD

**Issue by algotradingstrategies** [projectchicago/gastoken#30]
Is there also a gastoken contract deployed on polygon (matic network)? Or is there no gas refund mechanism in the polygon protocol, i.e. gastoken not possible there?

**Comment by k06a** [comment]
You could use CHI gas token, which should be a bit more efficient: https://polygonscan.com/token/0x0000000000004946c0e9f43f4dee607b0ef1fa1c

Source could be found here: https://github.com/1inch/chi
